# Generated by Django 5.2.1 on 2025-05-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctoravailability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'day_of_week', 'start_time', 'end_time')},
        ),
    ]
