# Generated by Django 5.2.1 on 2025-05-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctoravailability_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='certificate_document',
            field=models.FileField(blank=True, null=True, upload_to='doctor_certificates/'),
        ),
    ]
