# Generated by Django 5.2.1 on 2025-05-14 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctorprofileauditlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorProfileAuditLog',
        ),
    ]
