# Generated by Copilot on 2025-05-19
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('doctors', '0007_doctorprofileauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
